package aclt.genielog.rp.ihm;

/**
 * Il s'agit d'un componsant graphique regroupant tous les items utilisés
 * pour gérer les flux de voitures dans la simulation.
 * @author alexis
 */
public class fluxPanel extends javax.swing.JPanel {

    /**
     * Creates new form fluxPanel
     */
    public fluxPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titreLabel = new javax.swing.JLabel();
        nordLabel = new javax.swing.JLabel();
        nordSpinner = new javax.swing.JSpinner();
        nordButton = new javax.swing.JButton();
        ouestLabel = new javax.swing.JLabel();
        ouestSpinner = new javax.swing.JSpinner();
        ouestButton = new javax.swing.JButton();
        sudLabel = new javax.swing.JLabel();
        sudSpinner = new javax.swing.JSpinner();
        sudButton = new javax.swing.JButton();
        estLabel = new javax.swing.JLabel();
        estSpinner = new javax.swing.JSpinner();
        estButton = new javax.swing.JButton();
        crashButton = new javax.swing.JButton();

        titreLabel.setText("Flux :");

        nordLabel.setText("Nord :");

        nordButton.setText("Vider");

        ouestLabel.setText("Ouest :");

        ouestButton.setText("Vider");

        sudLabel.setText("Sud :");

        sudButton.setText("Vider");

        estLabel.setText("Est :");

        estButton.setText("Vider");

        crashButton.setText("Car crash");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crashButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titreLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ouestLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sudLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(estLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(estSpinner)
                                    .addComponent(sudSpinner, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ouestSpinner, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ouestButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sudButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(estButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nordSpinner)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nordButton)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nordLabel)
                    .addComponent(nordSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nordButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ouestLabel)
                    .addComponent(ouestSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ouestButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sudSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sudButton)
                    .addComponent(sudLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estLabel)
                    .addComponent(estSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crashButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crashButton;
    private javax.swing.JButton estButton;
    private javax.swing.JLabel estLabel;
    private javax.swing.JSpinner estSpinner;
    private javax.swing.JButton nordButton;
    private javax.swing.JLabel nordLabel;
    private javax.swing.JSpinner nordSpinner;
    private javax.swing.JButton ouestButton;
    private javax.swing.JLabel ouestLabel;
    private javax.swing.JSpinner ouestSpinner;
    private javax.swing.JButton sudButton;
    private javax.swing.JLabel sudLabel;
    private javax.swing.JSpinner sudSpinner;
    private javax.swing.JLabel titreLabel;
    // End of variables declaration//GEN-END:variables
}
