package aclt.genielog.rp.ihm;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import aclt.genielog.rp.lib.Flux;

/**
 * Il s'agit d'un componsant graphique regroupant tous les items utilisés
 * pour gérer les flux de voitures dans la simulation.
 *
 * @author Alexis Brenon
 * @author Cécilia Martin
 * @author Luc Chante
 * @author Tiphaine Teyssier
 */
public class FluxPanel extends javax.swing.JPanel {
	public FluxPanel() {
		initComponents();
		this.setVisible(true);
		nordButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				nordSpinner.setValue(0);
			}
		});
		estButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				estSpinner.setValue(0);
			}
		});
		sudButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				sudSpinner.setValue(0);
			}
		});
		ouestButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				ouestSpinner.setValue(0);
			}
		});
                crashButton.addActionListener(new ActionListener() {
			private final String[] titles = { "Crash", "Réparer" };
			private int status = 0;

			@Override
			public void actionPerformed(ActionEvent e) {
				status = (status + 1) % 2;
				crashButton.setText(titles[status]);
			}
		});
	}

	public void addAccidentListener(ActionListener voie) {
		crashButton.addActionListener(voie);
	}

	public void setListeners(final Flux nord, final Flux est, final Flux sud,
			final Flux ouest, Object crash) {
		nordSpinner.addChangeListener(nord);
		nordButton.addActionListener(nord);
		nordButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				nord.vidagePerformed(e);
			}
		});
		estSpinner.addChangeListener(est);
		estButton.addActionListener(est);
		estButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				est.vidagePerformed(e);
			}
		});
		sudSpinner.addChangeListener(sud);
		sudButton.addActionListener(sud);
		sudButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				sud.vidagePerformed(e);
			}
		});
		ouestSpinner.addChangeListener(ouest);
		ouestButton.addActionListener(ouest);
		ouestButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				ouest.vidagePerformed(e);
			}
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titreLabel = new javax.swing.JLabel();
        nordLabel = new javax.swing.JLabel();
        nordSpinner = new javax.swing.JSpinner();
        nordButton = new javax.swing.JButton();
        ouestLabel = new javax.swing.JLabel();
        ouestSpinner = new javax.swing.JSpinner();
        ouestButton = new javax.swing.JButton();
        sudLabel = new javax.swing.JLabel();
        sudSpinner = new javax.swing.JSpinner();
        sudButton = new javax.swing.JButton();
        estLabel = new javax.swing.JLabel();
        estSpinner = new javax.swing.JSpinner();
        estButton = new javax.swing.JButton();
        crashButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        titreLabel.setText("Flux :");

        nordLabel.setText("Nord :");
        nordLabel.setToolTipText("Voie du haut.");

        nordSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        nordSpinner.setToolTipText("Nombre de voitures arrivant de cette voie à chaque déplacement.");

        nordButton.setText("Vider");
        nordButton.setToolTipText("Réinitialiser le flux d'entrée.");

        ouestLabel.setText("Ouest :");
        ouestLabel.setToolTipText("Voie de gauche.");

        ouestSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        ouestSpinner.setToolTipText("Nombre de voitures arrivant de cette voie à chaque déplacement.");

        ouestButton.setText("Vider");
        ouestButton.setToolTipText("Réinitialiser le flux d'entrée.");

        sudLabel.setText("Sud :");
        sudLabel.setToolTipText("Voie du bas.");

        sudSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        sudSpinner.setToolTipText("Nombre de voitures arrivant de cette voie à chaque déplacement.");

        sudButton.setText("Vider");
        sudButton.setToolTipText("Réinitialiser le flux d'entrée.");

        estLabel.setText("Est :");
        estLabel.setToolTipText("Voie de droite.");

        estSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        estSpinner.setToolTipText("Nombre de voitures arrivant de cette voie à chaque déplacement.");

        estButton.setText("Vider");
        estButton.setToolTipText("Réinitialiser le flux d'entrée.");

        crashButton.setText("Crash");
        crashButton.setToolTipText("Créer un accident.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crashButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ouestLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sudLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estSpinner)
                            .addComponent(sudSpinner, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ouestSpinner, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ouestButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sudButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(estButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nordSpinner)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nordButton))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(titreLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nordLabel)
                    .addComponent(nordSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nordButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ouestLabel)
                    .addComponent(ouestSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ouestButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sudSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sudButton)
                    .addComponent(sudLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estLabel)
                    .addComponent(estSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crashButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crashButton;
    private javax.swing.JButton estButton;
    private javax.swing.JLabel estLabel;
    private javax.swing.JSpinner estSpinner;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton nordButton;
    private javax.swing.JLabel nordLabel;
    private javax.swing.JSpinner nordSpinner;
    private javax.swing.JButton ouestButton;
    private javax.swing.JLabel ouestLabel;
    private javax.swing.JSpinner ouestSpinner;
    private javax.swing.JButton sudButton;
    private javax.swing.JLabel sudLabel;
    private javax.swing.JSpinner sudSpinner;
    private javax.swing.JLabel titreLabel;
    // End of variables declaration//GEN-END:variables

	public interface ViderVoieListener {
		public abstract void vidagePerformed(ActionEvent e);
	}
}
