package aclt.genielog.rp.ihm;

import aclt.genielog.rp.Simulateur;
import java.awt.FlowLayout;
import javax.swing.JFrame;

/**
 * Fenêtre principale de l'application.
 * C'est l'agrégat de tous nos Panel et de quelques composants simples.
 * @author alexis
 */
public class SimulateurUI extends javax.swing.JFrame {

    /**
     * Creates new form SimulateurUI
     */
    public SimulateurUI(Simulateur simulateur) {
        initComponents();
        this.simulateur = simulateur;
        this.repaint();
    }

    /**
     * Callback appelé par le panel d'ajout de voitures.
     * @param nbVoitures Nombre de voitures à ajouter
     * @param entree Voie d'entrée des voitures
     * @param sortie Voie de sortie des voitures
     */
    /*public void ajouterVoitures (int nbVoitures, VoieEnum entree, VoieEnum sortie) {
        simulateur.ajouterVoitures(nbVoitures, entree, sortie);
    }*/

    /**
     * Callback appelé par le panel de modification de vitesse.
     * @param vitesse Nouvelle vitesse de simulation
     */
    public void changeVitesseSimu (int vitesse) {
        //simulateur.changeVitesseSimu(vitesse);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fluxPanel = new FluxPanel(this);
        ajoutPanel = new AjoutPanel(this);
        vitessePanel = new VitessePanel(this);
        jPanel2 = new javax.swing.JPanel();
        goButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        imagePanel = new RondPointPanel(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simuron");
        setName("simuronFrame"); // NOI18N
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridLayout(4, 1, 0, 16));

        fluxPanel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout fluxPanelLayout = new javax.swing.GroupLayout(fluxPanel);
        fluxPanel.setLayout(fluxPanelLayout);
        fluxPanelLayout.setHorizontalGroup(
            fluxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );
        fluxPanelLayout.setVerticalGroup(
            fluxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );

        jPanel1.add(fluxPanel);

        ajoutPanel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout ajoutPanelLayout = new javax.swing.GroupLayout(ajoutPanel);
        ajoutPanel.setLayout(ajoutPanelLayout);
        ajoutPanelLayout.setHorizontalGroup(
            ajoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );
        ajoutPanelLayout.setVerticalGroup(
            ajoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );

        jPanel1.add(ajoutPanel);

        vitessePanel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout vitessePanelLayout = new javax.swing.GroupLayout(vitessePanel);
        vitessePanel.setLayout(vitessePanelLayout);
        vitessePanelLayout.setHorizontalGroup(
            vitessePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );
        vitessePanelLayout.setVerticalGroup(
            vitessePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );

        jPanel1.add(vitessePanel);

        goButton.setText("Lecture");
        goButton.setToolTipText("Lancer/Arrêter la simulation.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(goButton, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(goButton, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel1.add(jPanel2);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        imagePanel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main (String args[]) {
        SimulateurUI ui = new SimulateurUI(new Simulateur(10));
        ui.setVisible(true);
        ui.pack();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ajoutPanel;
    private javax.swing.JPanel fluxPanel;
    private javax.swing.JButton goButton;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel vitessePanel;
    // End of variables declaration//GEN-END:variables
    private Simulateur simulateur;
}
